---
title: "Average Music Loudness in Latin America"
date: "by Michael R, 12/26/2018"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
#Loudness
library(leaflet)
options(digits=2)
south <- geojsonio::geojson_read("map.geojson", what = "sp", stringsAsFactors = FALSE)

var2 <- "Decibels"
south$loudness <- as.numeric(south$loudness)
var <- round(south$loudness, 2)

#print(south$africa)
#geojsonio::geojson_write(south, file = "map-7.geojson")
bins <- c(-1, -2, -3, -4, -5, -6, -30, -60)
pal <- colorBin("YlOrRd", domain = south$loudness, bins = bins)

m <- leaflet(south, width="100%", height = "600", options = leafletOptions(minZoom = 2, maxZoom = 5)) %>%
  setView(-65, -20, 3) %>%
  
  setMaxBounds( lng1 = -150
                , lat1 = -65
                , lng2 = 20
                , lat2 = 60 )%>%
  ##addTiles()
  addProviderTiles("MapBox", options = providerTileOptions(
    id = "mapbox.light",
    accessToken = Sys.getenv('pk.eyJ1IjoibWljaGFlbDEyMzY3MSIsImEiOiJjam56MjBlZXAwNDQyM2ttenVybW44cWFiIn0.l4JYw43bI6Ss1NJlJ-8Kdw')))

labels <- sprintf(
  "<strong>%s</strong><br/>%g %s",
  south$name, (var), var2
)
counting <- 0
for (i in labels)
{
  counting <- counting + 1
  if(!(length(i <- grep("-", i)))){
    #print (labels[counting])
    labels[counting] <- gsub("(<br/>).*", "\\1", labels[counting])
    #print (labels[counting])
    labels[counting] <- paste(labels[counting], "No data available.", sep = "")
    #print (labels[counting])
  }
}
labels <- labels %>% lapply(htmltools::HTML)
labels2 <- sprintf(
  '<iframe src="https://open.spotify.com/embed/playlist/%s" width="300" height="240" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>', south$name
)
# brazil : 68kJ4ASW7AWdDKMiC3C7mC
counting <- 0
for (i in labels2)
{
  counting <- counting + 1
  if(length(i <- grep(south$name[counting], i))){
    #print (labels[counting])
    labels2[counting] <- gsub(south$name[counting],
                              switch(south$name[counting],
                                     "Bahamas" = "37i9dQZF1DZ06evO2HEVwI",             
                                     "Belize"  = "3YNNQ0Iew4lWMxWGX6UtFj",              
                                     "Costa Rica"  = "37i9dQZF1DX6vA2dIuojVg",          
                                     "Cuba"  = "37i9dQZF1DXa8qiD2PG4FF",                
                                     "Dominican Republic"  = "1rJgueRMCIN6a501E6ydpJ",
                                     "Honduras"  = "1PSvOuqLUh2URCxq2shiNB",           
                                     "Haiti"   = "37i9dQZF1DX3XjJqhm9fqD",             
                                     "Guatemala"   = "67Hmd3UaBM7Po5hXkl1JoS",         
                                     "Jamaica"     = "5iRqvywCnUHGYKslcohxj4",         
                                     "Mexico"      = "1D54Nwb5Uvqdau9vDzsVco",        
                                     "Panama"  = "37i9dQZF1DZ06evO2ir6uw",
                                     "Nicaragua"  = "3zghD7KxYrIhkD9hM2o6zY",
                                     "Puerto Rico"  = "2kat6mu9ZbUQxY4N1knxKJ",
                                     "El Salvador"  = "6hMR732Qllr7t6Xo7x5J5D",
                                     "Argentina"   = "1RcPSrPqLpvgoBUldrLJAp",        
                                     "Trinidad and Tobago"  = "3H3jIhI9iY1RpAKvd1F11q",
                                     "Bolivia"   = "37i9dQZF1DXcU9MUSqc5Ok",           
                                     "Chile"   = "7lf5FhGfmUIXi8l2qc47WB",             
                                     "Ecuador"   = "1ddXIcsOCFZBd20P625L7o",           
                                     "Falkland Islands"    = "1y7E5GXSac77FzesM2ASjx",
                                     "Colombia"    = "7xy6dSSFD6N1vsN2774RvJ",         
                                     "Paraguay"    = "5LPEGIkBNEFifBc6NZhkXv",         
                                     "Peru"      = "5owR7sSGZ0cCE8E5gsNW8x",           
                                     "Suriname"    = "7FAkWpY7olWtvIztfBpTz2",         
                                     "Guyana"      = "2zsqgtV2SI7BcmxdI9R5IT",        
                                     "Uruguay"     = "4U8ivVB1T4vYhmUOduvrXW",         
                                     "Venezuela"   = "37i9dQZF1DWWekySnB4xpt",         
                                     "Brazil"      = "37i9dQZF1DX5lAV5ZGu9ik",         
                                     "French Guiana"  = "7bF4MT7HehPG1EfrRQykCT"
                                     )
                              , labels2[counting])
    #print (labels[counting])
    #labels2[counting] <- paste(labels[counting], "No data available.", sep = "")
    #print (labels[counting])
  }
}

labels2 <- labels2 %>% lapply(htmltools::HTML)
#print(labels2)
m %>% addPolygons(fillColor = ~pal(loudness),
  weight = 2,
  opacity = 1,
  options = pathOptions(interactive = TRUE),
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7,
  highlight = highlightOptions(
    weight = 5,
    color = "#666",
    dashArray = "",
    fillOpacity = 0.7,
    bringToFront = TRUE),
  popup = labels2,
  popupOptions = popupOptions(closeOnClick = TRUE),
  label = labels,
  labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "15px",
    direction = "auto"))%>%
 addLegend(pal = colorBin("YlOrRd", domain = south$loudness, bins = bins, reverse = FALSE), values = ~loudness, opacity = 0.7, title = "Average Loudness in Decibels<br>(Higher is Louder)",
    position = "bottomright",  labFormat = labelFormat(transform = function(x) sort(x, decreasing = TRUE)))
```
```{r results="asis", echo=FALSE, warning=FALSE, message=FALSE}
cat("
<style>
.leaflet-container {
    background: #FFF;
}
</style>
")
```
